### ISSUE TITLE
Fatal error: Uncaught TypeError: Argument 1 passed to {closure}() must be an instance of ConnectionInterface, instance of React\Socket\Connection given

### ISSUE THREAD

**Issue by vahidvdn** [reactphp/socket#173]
After running my server socket, I try to connect to them by `javascript` client. I get the error when I run my client.

index.php:
```
<?php
require 'vendor/autoload.php';

$loop = React\EventLoop\Factory::create();
$socket = new React\Socket\Server('127.0.0.1:8080', $loop);

$socket->on('connection', function (ConnectionInterface $conn) {
    $conn->write("Hello " . $conn->getRemoteAddress() . "!\n");
    $conn->write("Welcome to this amazing server!\n");
    $conn->write("Here's a tip: don't say anything.\n");

    $conn->on('data', function ($data) use ($conn) {
        $conn->close();
    });
});

$loop->run();
```

index.html:

```
<script>


var socket = new WebSocket('ws://localhost:8080');

// Open the socket
socket.onopen = function(event) {
    var msg = 'I am the client.';

    console.log('socket opened!');

    console.log('> ' + msg);

    // Send an initial message
    socket.send(msg);

    // Listen for messages
    socket.onmessage = function(event) {
        console.log('< ' + event.data);
        socket.close();
    };

    // Listen for socket closes
    socket.onclose = function(event) {
        console.log('Client notified socket has closed', event);
    };

    // To close the socket....
    //socket.close()

};


</script>
```

I get the following errors:

```
Fatal error: Uncaught TypeError: Argument 1 passed to {closure}() must be an instance of ConnectionInterface, instance of React\Socket\Connection given, called in C:\wamp64\www\socket-react\vendor\evenement\evenement\src\Evenement\EventEmitterTrait.php on line 123 and defined in C:\wamp64\www\socket-react\index.php:6
Stack trace:
#0 C:\wamp64\www\socket-react\vendor\evenement\evenement\src\Evenement\EventEmitterTrait.php(123): {closure}(Object(React\Socket\Connection))
#1 C:\wamp64\www\socket-react\vendor\react\socket\src\Server.php(47): Evenement\EventEmitter->emit('connection', Array)
#2 C:\wamp64\www\socket-react\vendor\evenement\evenement\src\Evenement\EventEmitterTrait.php(123): React\Socket\Server->React\Socket\{closure}(Object(React\Socket\Connection))
#3 C:\wamp64\www\socket-react\vendor\react\socket\src\TcpServer.php(233): Evenement\EventEmitter->emit('connection', Array)
#4 C:\wamp64\www\socket-react\vendor\react\socket\src\TcpServer.php(213): React\Socket\TcpServer->handleConnection(Resource id #25)
#5 C:\wamp6 in C:\wamp64\www\socket-react\index.php on line 6
```

**Comment by WyriHaximus** [comment]
Hey @vahidvdn looks like you didn't import the `ConnectionInterface` in your file or used the FQIN (`React\Socket\ConnectionInterface`) in your callable. By the looks of it you copied that code directly from our readme and we didn't include it there. I'll open a PR shortly resolving that.

Also it looks like you want to use websockets, this package does TCP sockets where HTTP and then websockets are build on top, we suggest https://github.com/ratchetphp/Ratchet for serving websockets.

**Comment by vahidvdn** [comment]
Hi @WyriHaximus. Thanks for the response. Yeah I forgot to import the `ConnectionInterface` by mistake. Now in client side I get the following error:
```
WebSocket connection to 'ws://localhost:8080/' failed: Error during WebSocket handshake: net::ERR_INVALID_HTTP_RESPONSE
```

Btw, I going to test your mentioned package for  serving websockets. Thanks.
